export const SITE = {
  website: "https://blog.molulu.top",
  author: "Mo1u",
  profile: "https://github.com/Mooo1u",
  desc: "Mo1u 的 Markdown 博客，基于 AstroPaper 与 Astro 构建，部署在 GitHub Pages。",
  title: "Mo1u's blog",
  subtitle: "这趟旅行若是开心，亦是无负这一生",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "编辑此页",
    url: "https://github.com/Mooo1u/Blog/edit/main/",
  },
  dynamicOgImage: false,
  dir: "ltr",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
} as const;
